name: build-sphinx-html

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build-sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: ammaraskar/sphinx-action@master
        name: Build Sphinx documentation
        with:
          docs-folder: "./"

     
      - uses: JamesIves/github-pages-deploy-action@v4.2.3
        name: Deploy 🚀
        with:
          branch: gh-pages
          folder: docs/build/html/
          clean: true
          single-commit: true