name: build-sphinx-html

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build-sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: ammaraskar/sphinx-action@master
        name: Build Sphinx documentation
        with:
          docs-folder: "./"
      - uses: actions/upload-artifact@v1
        name: Save html artifacts
        with:
          name: DocumentationHTML
          path: docs/build/html

     
      - uses: JamesIves/github-pages-deploy-action@v4.2.3
        name: Deploy 🚀
        with:
          branch: gh-pages
          folder: _site
          clean: true
          single-commit: true